name = "react-router-ssr-poc"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

# Build output folder
build = { command = "npm run build" }

# Cloudflare Pages Functions folder
pages_build_output_dir = "./build/client"
functions = "./functions"

[env.production]
vars = { NODE_ENV = "production" }
